### PR TITLE
Fix stack data disclosure when returning static files smaller than 16KiB

### PR DESCRIPTION
**Pull request by mrozigor**
It could also cause to return partially incorrect file ending in
case of file not being rounded up to 16KiB.

Thanks to Gynvael Coldwind and hebi for discovering and preparing
report.

### CODE REVIEW

**Comment by luca-schlecker** [comment]
Is there a reason that the `buffers` vector is inside the loop?

**Comment by mrozigor** [comment]
It was already implemented like this. It looks like `asio::write` expects vector of buffers. Also it looks like `asio::buffer` doesn't own memory (https://think-async.com/Asio/asio-1.22.1/doc/asio/reference/buffer.html#asio.reference.buffer.buffer_invalidation), so we have to:

- send it buffers vector immediately with only one buffer and then use existing array to load next part of a file (current solution)

- copy memory from array (or maybe load data directly to `asio::buffer`) with use of (I guess) `asio::buffer_copy` (https://think-async.com/Asio/asio-1.22.1/doc/asio/reference/buffer_copy.html)

**Review by luca-schlecker — DISMISSED** [review]
I see, the current solution works fine, no need to add extra copy-operations.

LGTM 👍

**Comment by mrozigor** [comment]
I'll leave it till tomorrow and then merge. Thanks!

**Comment by MichaelSB** [comment]
The vector with size 1 could be constructed outside the loop. And then the asio::buffer would be assigned to the first element in the vector inside the loop. Imo. No copy needed and we would save construction/destruction of a vector in a loop (probably alloc/dealloc)

**Comment by mrozigor** [comment]
Good point. I didn't want to change anything not connected directly with error, but maybe postponing it is a worse idea :P

**Review by The-EDev — APPROVED** [review]

**Pull request merged**
