### PR TITLE
Ignore NaN and infinite values in json::wvalue

### PR DESCRIPTION
**Pull request by Vhuynh25**

### CODE REVIEW

**Comment by epajarre** [comment]
Sorry to jump into the middle, but does the change cause broken json to be
generated?

The number is completely missing from the output. (My apologies, if not, I
have not actually tested this). Causing adjacent commas in arrays and
broken json objects.

I do not have a good solution to this, maybe output 0 or a "very large
number", although I might actually prefer null so that it would not be
"syntax broken", but "value broken".

I guess correctly removing the value from an object, by also removing the
name of the value would be OK, but I don't see any nice way for handling
arrays, because the meaning of a missing value depends on the application,
it might be insignificant or it may change the remaining data completely.

 Eero

**Comment by The-EDev** [comment]
@epajarre #315 did output `null` instead of omitting the value outright, unfortunately either returning null or omitting the value will cause headaches to an unsuspecting developer, hence the warning.

Whether or not this PR would cause broken syntax or not I've yet to test. But I will look into it.

**Comment by The-EDev** [comment]
@epajarre I've recently had time to test the PR and you were right, it does seem to produce incorrect JSON whether the invalid value is in an object or an array.

It seems that omitting the value (and key) properly will take more work than just outputting `null`. That and the Array use case make me rethink my stance on #315. It might actually be best to replace an invalid number with `null` while still sending out a warning which explains that the invalid value was replaced with `null`.

@Vhuynh25 I am very sorry for this change in scope and taking your time, Would you be interested in changing your code to output `null` instead of simply doing nothing when an invalid value is detected (and change the warning message accordingly).

Additionally for some reason I couldn't compile Crow locally until I changed `cmath` to `math.h`. I'm not sure why that was a problem but I'd appreciate it if you could look into that.

**Comment by The-EDev** [comment]
Thank you for your help, and for adapting your code to the change in scope.

I'll run my local tests to check that everything is in order (and possibly push those tests as unit tests) and merge the PR.

**Review by The-EDev — APPROVED** [review]

**Pull request merged**
