### PR TITLE
feat: support signal handlers

### PR DESCRIPTION
**Pull request by xstar2091**
add handlers when calling signal_add function. The handlers will be called in the order in which they were added

### CODE REVIEW

**Comment by xstar2091** [comment]
The tests failed unfortunately. I don't have a Mac or Windows device, so there's no way to troubleshoot these errors.

**Comment by xstar2091** [comment]
How can I continue the merge request? Why other reviewers don't review

**Comment by xstar2091** [comment]
Is there any one to review this merge request?

**Comment by The-EDev** [comment]
The tests seem to be working...

**Comment by gittiver** [comment]
I would not put the signal handlers this way into Crow itself. Its not a correct solution as the are called out of band.

**Comment by xstar2091** [comment]
> Would it be possible to add an example for creating a new signal handler? It would be best for this feature to be documented.

I do not know what is corrent way to call in bound and no one explained it

**Pull request closed without merging**
