### PR TITLE
Fixed multiple definition issues

### PR DESCRIPTION
**Pull request by fckxorg**
Multiple definition error fix:
1) Inlined functions that were not inlined
2) Added CROW_MAIN_ macro, which should be placed in main.cpp file. This macro helps avoid multiple definition error of static variables

### CODE REVIEW

**Review by The-EDev — CHANGES_REQUESTED** [review]
Thanks for your work. One thing to note is that it seems you committed test logs.

Also does this fix #110 ?

**Comment by fckxorg** [comment]
Yes, it fixes #110

**Review by The-EDev — CHANGES_REQUESTED** [review]
Sorry but I also just noticed the file `include/crpw/tags`, I'm guessing it's auto generated as well

**Review by The-EDev — APPROVED** [review]
Great job. I'll merge this once we make the switch from travis and ran the tests.

**Comment by rittelle** [comment]
Thanks!
Is there a reason for the trailing underscore in `CROW_MAIN_`? Would `CROW_MAIN_` work, too?

**Comment by fckxorg** [comment]
Well, there is no specific reason for that trailing underscore to be there, but it's just the way I usually define macros like that. If it doesn't seem convenient for you, I can remove it.

**Comment by rittelle** [comment]
It's just uncommon to name macros that are part of an API with a trailing underscore as far as I can tell.
Crow's other Macros like `CROW_STATIC_DIRECTORY` don't contain one aswell.
So it's more a matter of consistency than convinience.

**Review by The-EDev — APPROVED** [review]

**Comment by The-EDev** [comment]
@fckxorg could you please make an empty commit just to trigger CI? Thanks

**Comment by The-EDev** [comment]
I'm sorry, it seems you need to merge master into the PR for CI to work. I apologize for giving the wrong instructions.

**Pull request merged**
