### PR TITLE
Get app port

### LINKED ISSUE #275: Get automatically assigned port after startup
I am running crow in a background thread and want to get the automatically assigned port (`app.port(0)`) after startup. 
Is there a way to access the port from the app object?

Thank you for your time.

### PR DESCRIPTION
**Pull request by nx10**
Fixes #275 .

### CODE REVIEW

**Comment by The-EDev** [comment]
Thanks for the PR, although the unit test would probably need to use an automatically assigned port

**Comment by nx10** [comment]
Do you mean by setting up a custom logger that parses the inital status message or just checking `port != 0`?

**Comment by The-EDev** [comment]
Looking at the code again, your test looks just fine, sorry about the confusion.

**Comment by nx10** [comment]
Thanks! It's ready to be merged.

**Review by The-EDev — APPROVED** [review]

**Comment by The-EDev** [comment]
All good, Thanks for your help!

**Pull request merged**
