### PR TITLE
Added HTTP compression using gzip or deflate

### LINKED ISSUE #46: Zlib HTTP compression
ipkn#144

Should support compression and decompression for http requests.

This could be needed before HTTP/2 could be implemented.

### PR DESCRIPTION
**Pull request by The-EDev**
(disabled by default, requires calling method)

Thanks to @pierobot with his/her work on ipkn#144, the core code is for compressing/decompressing, plus the algorithm selection is his/hers

closes #46

### CODE REVIEW

**Comment by The-EDev** [comment]
Found a bug, it doesn't consider compressing files, will close until it is fixed

**Comment by The-EDev** [comment]
The problem here is streaming, so the way it works is whatever file / response body is split into 16KiB chunks and then sent down the TCP connection.

Each of these chunks would have to be added to the `z_stream` and deflated individually before being sent.

The current implementation runs on 1 string and returns 1 string, thus it would need to be split so that a new stream isn't created for every chunk, and the same stream can be used without having to copy the whole file / body into memory.

**Comment by The-EDev** [comment]
I think for now it's best to disable gzip when streaming a response (whether it's static files or large responses), maybe will be added with websocket compression

**Review by mrozigor — APPROVED** [review]

**Comment by D-Latch** [comment]
Hi I think there might be something wrong with the action above ('I think for now it's best to disable gzip when streaming a response (whether it's static files or large responses)').
No matter how I set 'compressed' flag to false I still find header 'Content-Encoding' in my response. So I assumed that the authentic response returned is not the one I define but the one that is copied from it. Thus I thought compressed flag might forgot to be set in the copy-construct function and finally I got this:

**Pull request merged**
