### PR TITLE
Blueprint middleware

### PR DESCRIPTION
**Pull request by dranikpg**
Hi! I've spent the last weekend experimenting with type quirks for middleware, but am happy to anounce that this one I found an unversal and simple solution for both handlers and blueprints.

## Goals

1. Support blueprint middleware with minimal friction with something like

```c++
Blueprint<Mw1, Mw2> bp;
```

or 

```c++
bp.CROW_MIDDLEWARES(app, Mw1, Mw2);
```

2. Keep all other middleware intact without any changes

## What it looks like

```c++
crow::App<FirstMW, SecondMW, ThirdMW> app;

crow::Blueprint bp1("a", "c1", "c1");
bp1.CROW_MIDDLEWARES(app, FirstMW);

crow::Blueprint bp2("b", "c2", "c2");
bp2.CROW_MIDDLEWARES(app, SecondMW);

CROW_BP_ROUTE(bp2, "/") 
    .CROW_MIDDLEWARES(app, ThirdMW)
    ([](const crow::request& req) {
      return "";
    });

bp1.register_blueprint(bp2);
app.register_blueprint(bp1);
```

The tree looks like `bp1[FirstMW] -> bp2[SecondMW] -> handler[ThirdMW]`, so it calls all of FirstMW, SecondMW, ThirdMW.

## How it works

Blueprints differ greatly from handlers. First and foremost, they can be **nested**. This means that in a deep blueprint tree, we have to pick up all the middleware on the way to the handler. They can be passed around and stored in homogeneous containers, so that all type-heavy mud will be a burden to users. 

After some experiments, I decied it would be a lot easier and more productive leaving the strong type system behind and making middleware more "dynamic", but hidden behind a typesafe layer.

The `BaseRule` now stores its middleware directly:
```c++
class BaseRule {
  middleware_indices mw_indices_;
}
```
in `middleware_indices` -  a type-safe wrapper over a basic vector of middleware indices. It checks that the requested middleware is part of the App and computes its index.
```c++
template<typename App, typename MW, typename... Middlewares>
void push() {
  static_assert(black_magic::has_type<MW, typename App::mw_container_t>::value, 
    "Middleware must be present in app");
  indices_.push_back(black_magic::tuple_index<MW, typename App::mw_container_t>::value);
  push<App, Middlewares...>();
}
```
`Blueprint`s now essentially do the same - they just store all registered middleware in `middleware_indices`. As we walk down the blueprint and register handlers, we just merge all the indices, including the handlers ones.

Great, now every handler knows what middleware it has to invoke (including his own and blueprints). But we have erased all the types to make managing middleware easier. How do we get them back? I thought about either templatizing validation or handling in the router. And went for the second more straightforward approach.

`router->handle` is now parameterized by the app itself calls `handle_rule`, of which there are two versions:
```c++
template<typename App>
enable_if<App::middlewares == 0> handle_rule(...) { /* just handle rule */ }

template<typename App>
enable_if<App::middlewares != 0> handle_rule(...) {
   if (!rule->mw_indices_.empty()) {
     // invoke middleware
     // register after handlers
   }
   // handle rule
}
```
The middleware invokation works exactly like in the old [`handler_middleware_wrapper`](https://github.com/CrowCpp/Crow/blob/03f2e266c15691cde0461ca72d1312c13ca93b42/include/crow/middleware.h#L257). But which CallCriteria do we use now? It no longer uses dependent types, but a simple function

The call helpers have changed to this
```c++
// unpack all middlewares recursively
template<int N, typename Middlewares>
bool middleware_call_helper()
{ 
  // check each if it is enabled
  if (cc.template enabled<CurrentMW>(N))
  { // call it }
}
```

And the dynamic criteria looks the following (without optimizations):
```c++
struct middleware_call_criteria_dynamic
{
  template<typename>
  const bool enabled(int i) const
  {
    return std::find(indices_.begin(), indices_.end(), i) != indices_.end();
  }
  const std::vector<int>& indices_;
};
```

There is no distinction between between blueprint and per-handler middleware, both work now the same and are universal "customizable & dynamic" middleware.  

Hooray! We can now use our middleware eveywhere we want.

## Issues

1. Instead of using indices, we can use [type_ids](https://en.cppreference.com/w/cpp/language/typeid). We can no longer check whether the listed middleware is part of the app at compile time (but at least crash at runtime 😆 ), but the user doesn't have to specify the app and can re-use middleware on different apps. Seems more universal but less safe to me.

2. ~~Make `middleware_call_criteria_dynamic` check for O(1)~~

3. Router->handle is now a template.

### CODE REVIEW

**Review by The-EDev — APPROVED** [review]
It might be a good idea to add an example as well as the unit test.

Other than that and the comments about documentation everything seems to be in order, and the description seems to be accurate in relation to the code changes. Although I should mention I'm not the most qualified when it comes to complex (at least complex for me) C++ code, and would appreciate if @luca-schlecker or @mrozigor could take a look at the code provide a third opinion.

If you guys are too busy or not interested I think this PR can be merged without too much issue. 

I'm sorry this review took so long, Thank you very much @dranikpg for the great work and for your patience!

**Comment by The-EDev** [comment]
@dranikpg it also seems some merge conflicts came up, could you please take a look at them? (let me know if you're too busy and I'll try to resolve them :))

**Comment by dranikpg** [comment]
> as well as the unit test

Unit test is already there, I'll add an example

> merge conflicts

I'll handle them this evening

**Review by The-EDev — APPROVED** [review]

**Comment by mrozigor** [comment]
I've looked at this and haven't found any problems ;)

**Pull request merged**
