### PR TITLE
Similar to Flask decorator for Method @app.route('/route', methods = ['POST'])

### PR DESCRIPTION
**Pull request by xhimanshuz**
It is more exressive like a Flask decorator for using methods like @app.route('/route', methods = ['POST'])
rather than using CROW_ROUTE(app, "/route").methods(HTTPMethod::POST),
CROW_ROUTE_M(app, "/route", HTTPMethod::POST) is more expressive
to users.

Before:
```cpp
    CROW_ROUTE(app, "/a").methods(HTTPMethod::POST)
    ([]() {
         return "Hello";
     });
```
After
```cpp    
CROW_ROUTE_M(app, "/a", HTTPMethod::POST)
    ([]() {
         return "Hello";
     });
```

Even I have created issue for this improvement.
Issue: #170

### CODE REVIEW

**Comment by The-EDev** [comment]
Thanks for not only making the suggestion but taking the time to implement it. I do however have some concerns, primarily the fact that you have a named parameter in Flask making it very clear that these are the methods (which IMO make the old version closer to flask), and that with the new way only 1 method can be applied, as opposed to both the old way and flask.

While I absolutely appreciate your work, I think the old `.methods()` way is better
@mrozigor what do you think?

**Comment by mrozigor** [comment]
I think that with @xhimanshuz solution you should be able to pass more than one method.

`CROW_ROUTE_M(app, "/a", (HTTPMethod::POST, HTTPMethod::GET))
([]() {
  return "Hello";
});`

Those parentheses look a little bit ugly, but it should work.

**Comment by The-EDev** [comment]
>  you should be able to pass more than one method.

I didn't know that, Thanks for letting me know. Although I still think the old solution is more elegant.

**Comment by xhimanshuz** [comment]
Thanks all, I'm not changing existing one, just adding one more option to the users.

**Comment by xhimanshuz** [comment]
> I think that with @xhimanshuz solution you should be able to pass more than one method.
> 
> ```
> CROW_ROUTE_M(app, "/a", (HTTPMethod::POST, HTTPMethod::GET))
> ([]() {
>   return "Hello";
> });
> ```
> 
> Those parentheses look a little bit ugly, but it should work.

**Maybe more like this, {} using initiation list**
```cpp
CROW_ROUTE_M(app, "/a", {HTTPMethod::POST, HTTPMethod::GET})
([]() {
  return "Hello";
});
```

**Comment by crisclacerda** [comment]
You can use compound literals and one variadic macro on top of this new macro to hide these constructs. Also if you use a struct to receive the parameters from designated initializers from this top-level macro you get named arguments with a default value for free.
Although I don't see any advantage on that since the original macro with two parameters already has the default values set. And the HTTPMethod:: in front of the method name is IMHO expressive enough. 

Slightly off-topic but what is the point of these macros in the first place? Why can't we have something like 
`app.route("/", [ ]( ){  });`

**Comment by xhimanshuz** [comment]
Actually, I was also thinking about it. It seems like flask way also.

> You can use compound literals and one variadic macro on top of this new macro so can pass more methods completely transparently. Also if you use a struct to receive the parameters from designated initializers from this top-level macro you get named arguments with a default value for free.
> Although I don't see any advantage on that since the original macro with two parameters already has the default values set. And the HTTPMethod:: in front of the method name is IMHO expressive enough.
> 
> Slightly off-topic but what is the point of these macros in the first place? Why can't we have something like
> `app.route("/", [ ]( ){ });`

**Comment by The-EDev** [comment]
> Slightly off-topic but what is the point of these macros in the first place? Why can't we have something like
app.route("/", [ ]( ){ });

You actually can, AFAIK the macro was put in place because MSVC versions 2013 or older didn't work with the default route function, so `dynamic_route` had to be used instead, on top of other workarounds.

**Comment by The-EDev** [comment]
Closing this for now, If anyone else believes this approach is better than `.methods()` then we can reopen this discussion.

**Pull request closed without merging**
