### PR TITLE
Replace `dumb_timer_queue` with new `task_timer`

### LINKED ISSUE #264: Apps are not independent of each other due to `dumb_timer_queue`.
`dumb_timer_queue::tick` is shared between all apps, leading them to influence each other.
https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/dumb_timer_queue.h#L17-L20
https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/app.h#L120-L125

`dumb_timer_queue` notably appears in the following files:
- [http_server.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/http_server.h)
- [http_connection.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/http_connection.h)
- [app.h](https://github.com/CrowCpp/Crow/blob/6f2eedaf9bcae84c91a419b0c86d87284235d982/include/crow/app.h)

### PR DESCRIPTION
**Pull request by luca-schlecker**
Signed-off-by: Luca Schlecker <luca.schlecker@hotmail.com>

It fixes #264 and lays the ground for #273 and #257.

This PR completely substitutes `dumb_timer_queue` for a new class named `task_timer`.
The advantages include:
- Ability to use a custom timeout for each task (function call)
- Doesn't use a static tick delay shared between all instances.
- Moved `io_service` logic into this class where it in my opinion should belong. (Moved from [`http_server.h`](https://github.com/CrowCpp/Crow/blob/22d39183450e6e5162aab376f4937ff887cd3c67/include/crow/http_server.h#L112-L120))
- Unit test for `task_timer`

### CODE REVIEW

**Review by The-EDev — CHANGES_REQUESTED** [review]
Functionally I don't see anything wrong. Though it might be a good idea to inline methods like `get_default_timeout()` or `set_default_timeout()`. 
Other than that I do have a couple things to point out. The first is that GCC gives a reorder warning when compiling, I'm guessing this is because of where `timeout` is placed in `http_server.h`.

The second is purely visual, and is about the comment style, since crow uses the following style:
```
/// Brief Description Here
///
/// Loooooong Description
```
And `\` instead of `@` for commands.

Lastly looking at this image:
image
`\return` might not work as you intended (I'm not 100% sure, it seems weird that the return type is there and there's a returns part). And there are a few places where a line break isn't showing (probably requires a `<br>`).

I'm sorry if any of the points are wrong or not explained well enough. Besides them the code seems quite good and running the tests and examples it seems to work as intended.

**Comment by luca-schlecker** [comment]
Isn't a member function with its body defined inside the class implicitly an inline function?
[_"A function defined entirely inside a class/struct/union definition, whether it's a member function or a non-member friend function, is implicitly an inline function." (cppreference.com)_](https://en.cppreference.com/w/cpp/language/inline)
It looks like in the screenshot of Doxygen you've sent, these functions are already classified as `inline`, supporting the above point.

I've seen that warning too, I'll look into it.

I'll change the comment style to align with Crow's style.

**Review by The-EDev — APPROVED** [review]
Everything seems good now. Great job!

P.S. If you want to force push your changes to get rid of the commits let me know, otherwise I guess we can merge this.

**Comment by luca-schlecker** [comment]
I think it should be fine. 🚀

**Pull request merged**
