### PR TITLE
OSSFuzz Integration

### PR DESCRIPTION
**Pull request by capuanob**
Hello! Apologies for the long delay in getting this implemented, as discussed in [Issue 744](https://github.com/CrowCpp/Crow/issues/744) with @gittiver. 

I would greatly appreciate your review and integration of this PR.

As an overview of what next steps are for me to integrate this project fully into OSSFuzz:

1. Once this is merged, I will submit a Dockerfile to google/oss-fuzz for continuous fuzz-testing of the defined harnesses
2. Once Google merges in the Dockerfile, the project is ready to fuzz!

Please let me know if there are any questions or concerns!

### CODE REVIEW

**Comment by gittiver** [comment]
Building the fuzzers on GitHub has a problem, do you have an idea what is going wrong?

**Comment by capuanob** [comment]
> Building the fuzzers on GitHub has a problem, do you have an idea what is going wrong?

@gittiver The OSSFuzz CI build will fail until this PR is merged and until I get approval for a subsequent, dependent PR to google/oss-fuzz. It is currently trying to retrieve these fuzz files from the default branch of the repository, but it is not yet there (bit of a chicken and the egg problem).

**Comment by gittiver** [comment]
so we have to wait for the other approval?

**Comment by gittiver** [comment]
> This PR needs to be merged first. Once you merge it, I will work with OSS-Fuzz to begin fuzzing!
So it will not break the build on main branch on merge? It's hard to check if it will work before merging int.

**Comment by capuanob** [comment]
It will try to build on merges as is, so it will show as a fail for the
CIFuzz job. It won't have an affect on any other jobs, though- so you could
just ignore the CIFuzz job until it is fully integrated with OSS-Fuzz
(Hopefully within a week's time).

**Review by gittiver — APPROVED** [review]

**Pull request merged**
